# Generated by Django 5.0.3 on 2024-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(default='/assets/tube-prev.png', upload_to='snippet')),
                ('resource_link', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
