# Generated by Django 5.0.3 on 2024-03-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
