# Generated by Django 5.0.3 on 2024-03-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resource_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_link',
            new_name='url',
        ),
    ]
