# Generated by Django 5.0.3 on 2024-03-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_resource_link_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(default='Video', max_length=20),
        ),
    ]
