# Generated by Django 5.0.3 on 2024-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_resource_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("event_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="resource",
            name="thumbnail",
            field=models.CharField(
                default="static/assets/Frameblog2.png", max_length=300
            ),
        ),
    ]
