# Generated by Django 5.0.3 on 2024-09-19 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="resource",
            name="video_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
